# Generated by Django 3.0.5 on 2023-09-07 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasting_specific_field', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_specific_field', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.Product')),
                ('producer', models.CharField(blank=True, max_length=200, null=True)),
                ('denomination', models.CharField(blank=True, max_length=200, null=True)),
                ('grape_variety', models.CharField(blank=True, max_length=200, null=True)),
                ('crianza', models.CharField(blank=True, max_length=200, null=True)),
            ],
            bases=('store.product',),
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.RemoveField(
            model_name='product',
            name='crianza',
        ),
        migrations.RemoveField(
            model_name='product',
            name='denomination',
        ),
        migrations.RemoveField(
            model_name='product',
            name='grape_variety',
        ),
        migrations.RemoveField(
            model_name='product',
            name='producer',
        ),
        migrations.AddField(
            model_name='tour',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.Product'),
        ),
        migrations.AddField(
            model_name='tasting',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.Product'),
        ),
    ]
