# Generated by Django 3.0.5 on 2023-09-07 17:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20230907_1706'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasting',
            old_name='event',
            new_name='cata',
        ),
        migrations.RenameField(
            model_name='tour',
            old_name='event',
            new_name='ruta',
        ),
        migrations.RemoveField(
            model_name='wine',
            name='product_ptr',
        ),
        migrations.AddField(
            model_name='wine',
            name='id',
            field=models.AutoField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wine',
            name='wine',
            field=models.OneToOneField(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='store.Product'),
            preserve_default=False,
        ),
    ]
